version: "3"

services: 
  web:
    build: .
    ports:
      - "3000:3000"
    command: yarn dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on: 
      - db
  db:
    image: postgres
    ports:
      - "8001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: